# SPDX-FileCopyrightText: 2024 Benedikt Bastin
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "eolmon"
version = "0.4.3"
edition = "2021"

[dependencies]
bollard = "0.16.1"
chrono = { version = "0.4.38", features = ["now", "serde"] }
clap = { version = "4.5.11", features = ["derive"] }
log = "0.4.22"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
simple_logger = "5.0.0"
tokio = { version = "1.39.1", features = ["full"] }

[dev-dependencies]
tempfile = "3.10.1"
